name: jasset
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  basic_utils: ^5.7.0
  dartz: ^0.10.1
  device_info_plus: ^9.1.1
  dio: ^5.3.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_form_builder: ^9.1.1
  flutter_lints: ^3.0.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  form_builder_validators: ^9.1.0
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  lottie: ^2.7.0
  native_barcode_scanner: ^1.0.6
  permission_handler: ^11.1.0
  qrcode_reader_web: ^1.1.1
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont_slnt,wght.ttf
  # Enable generation of localized Strings from arb files.
  

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - .env
    - assets/images/logoTelkom.png
    - assets/fonts/Nunito/
    - assets/fonts/Inter/
    - assets/images/Image.png
    - assets/icons/scan.png
